version: '3.8'

services:
  landing:
    build: .
    container_name: mun-landing
    restart: unless-stopped
    ports:
      - "13000:3000"  # Map to different port to avoid conflicts with main app
    volumes:
      - ./data:/app/data  # Persist email data
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s